<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Action extends Model
{
    protected $guarded = [];

    protected $casts = [
        'products_include_ids' => 'array',
        'products_exclude_ids' => 'array',
        'products_related_ids' => 'array',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::updated(function ($action) {
            \Cache::forget('actions');
        });

        self::deleted(function ($action) {
            \Cache::forget('actions');
        });
}

}
